import { products } from "./catalog";

export const branchTypes=["WAREHOUSE","STORE"] as const;
export const movementTypes=["STOCK_IN","SALE","ORDER_RESERVATION","ORDER_RELEASE","ORDER_FULFILLMENT","TRANSFER_OUT","TRANSFER_IN","RETURN","DAMAGED","ADJUSTMENT","INITIAL_STOCK"] as const;
export const transferStatuses=["DRAFT","REQUESTED","APPROVED","IN_TRANSIT","RECEIVED","CANCELLED"] as const;
export type MovementType=typeof movementTypes[number];
export type TransferStatus=typeof transferStatuses[number];
export type StaffRole="SUPER_ADMIN"|"ADMIN"|"WAREHOUSE_MANAGER"|"BRANCH_MANAGER"|"SALES_STAFF";
export type Branch={id:string;name:string;slug:string;code:string;type:"WAREHOUSE"|"STORE";address:string;phone?:string;active:boolean};
export type InventoryItem={id:string;branchId:string;productId:string;variantId?:string;variantName:string;quantity:number;reservedQuantity:number;minimumStock:number;updatedAt:string};
export type Movement={id:string;branchId:string;productId:string;variantId?:string;type:MovementType;quantity:number;quantityBefore:number;quantityAfter:number;referenceType?:string;referenceId?:string;note?:string;createdById?:string;createdAt:string};
export type TransferItem={productId:string;variantId?:string;requestedQuantity:number;shippedQuantity:number;receivedQuantity:number};
export type Transfer={id:string;transferNumber:string;fromBranchId:string;toBranchId:string;status:TransferStatus;createdById?:string;approvedById?:string;receivedById?:string;note?:string;items:TransferItem[];createdAt:string;shippedAt?:string;receivedAt?:string};
export type Audit={id:string;userId?:string;action:string;entityType:string;entityId:string;before?:unknown;after?:unknown;metadata?:unknown;ip?:string;createdAt:string};
type State={branches:Branch[];inventory:InventoryItem[];movements:Movement[];transfers:Transfer[];audits:Audit[];transferSequence:Record<number,number>;orderActions:Set<string>};

export const demoBranches:Branch[]=[
  {id:"merkezi-anbar",name:"BANTİK Mərkəzi Anbar",slug:"merkezi-anbar",code:"WH-001",type:"WAREHOUSE",address:"Bakı",phone:"+994 12 555 01 01",active:true},
  {id:"28-may",name:"BANTİK 28 May",slug:"28-may",code:"BR-001",type:"STORE",address:"Bakı, 28 May",phone:"+994 50 555 01 02",active:true},
  {id:"genclik-mall",name:"BANTİK Gənclik",slug:"genclik-mall",code:"BR-002",type:"STORE",address:"Bakı, Gənclik Mall",phone:"+994 50 555 01 03",active:true},
  {id:"nerimanov",name:"BANTİK Nərimanov",slug:"nerimanov",code:"BR-003",type:"STORE",address:"Bakı, Nərimanov",phone:"+994 50 555 01 04",active:true},
];
const quantities=[0,2,4,7,15,30];
const initialInventory=products.flatMap((product,pIndex)=>demoBranches.map((branch,bIndex)=>({id:`${branch.id}-${product.id}`,branchId:branch.id,productId:product.id,variantId:`${product.id}-default`,variantName:product.volumes[0]||product.colors[0]?.name||"Standart",quantity:quantities[(pIndex*3+bIndex)%quantities.length],reservedQuantity:0,minimumStock:3,updatedAt:new Date(0).toISOString()})));
const globalInventory=globalThis as typeof globalThis&{__bantikInventory?:State};
const initialState:State={branches:structuredClone(demoBranches),inventory:initialInventory,movements:[],transfers:[],audits:[],transferSequence:{},orderActions:new Set()};
export const inventoryState:State=globalInventory.__bantikInventory??initialState;globalInventory.__bantikInventory=inventoryState;
export const available=(item:InventoryItem)=>item.quantity-item.reservedQuantity;
export const stockStatus=(item:InventoryItem)=>available(item)<=0?"OUT_OF_STOCK":available(item)<=item.minimumStock?"LOW_STOCK":"IN_STOCK";
function itemFor(branchId:string,productId:string,variantId?:string){const item=inventoryState.inventory.find(x=>x.branchId===branchId&&x.productId===productId&&(!variantId||x.variantId===variantId));if(!item)throw new Error("Stok sətri tapılmadı");return item}
function audit(action:string,entityType:string,entityId:string,before:unknown,after:unknown,userId?:string,metadata?:unknown){inventoryState.audits.unshift({id:crypto.randomUUID(),action,entityType,entityId,before,after,userId,metadata,createdAt:new Date().toISOString()})}
function movement(item:InventoryItem,type:MovementType,delta:number,before:number,options:{referenceType?:string;referenceId?:string;note?:string;createdById?:string}={}){const row:Movement={id:crypto.randomUUID(),branchId:item.branchId,productId:item.productId,variantId:item.variantId,type,quantity:delta,quantityBefore:before,quantityAfter:item.quantity,...options,createdAt:new Date().toISOString()};inventoryState.movements.unshift(row);return row}
function ensurePositive(value:number,label="Miqdar"){if(!Number.isInteger(value)||value<=0)throw new Error(`${label} müsbət tam ədəd olmalıdır`)}
export function receiveStock(input:{branchId:string;productId:string;variantId?:string;quantity:number;referenceId?:string;note?:string;userId?:string}){ensurePositive(input.quantity);const item=itemFor(input.branchId,input.productId,input.variantId),before=item.quantity;item.quantity+=input.quantity;item.updatedAt=new Date().toISOString();movement(item,"STOCK_IN",input.quantity,before,{referenceType:"RECEIVING",referenceId:input.referenceId,note:input.note,createdById:input.userId});audit("STOCK_RECEIVED","Inventory",item.id,{quantity:before},{quantity:item.quantity},input.userId,input);return item}
export function adjustStock(input:{branchId:string;productId:string;variantId?:string;physicalQuantity:number;reason:string;userId?:string}){if(!input.reason.trim())throw new Error("Düzəliş səbəbi məcburidir");if(!Number.isInteger(input.physicalQuantity)||input.physicalQuantity<0)throw new Error("Stok mənfi ola bilməz");const item=itemFor(input.branchId,input.productId,input.variantId);if(input.physicalQuantity<item.reservedQuantity)throw new Error("Fiziki stok rezervdən az ola bilməz");const before=item.quantity;item.quantity=input.physicalQuantity;item.updatedAt=new Date().toISOString();movement(item,"ADJUSTMENT",item.quantity-before,before,{note:input.reason,createdById:input.userId});audit("STOCK_ADJUSTED","Inventory",item.id,{quantity:before},{quantity:item.quantity},input.userId);return item}
export function damageStock(input:{branchId:string;productId:string;variantId?:string;quantity:number;note:string;userId?:string}){ensurePositive(input.quantity);if(!input.note.trim())throw new Error("Zədə qeydi məcburidir");const item=itemFor(input.branchId,input.productId,input.variantId);if(available(item)<input.quantity)throw new Error("Kifayət qədər available stok yoxdur");const before=item.quantity;item.quantity-=input.quantity;item.updatedAt=new Date().toISOString();movement(item,"DAMAGED",-input.quantity,before,{note:input.note,createdById:input.userId});audit("STOCK_DAMAGED","Inventory",item.id,{quantity:before},{quantity:item.quantity},input.userId);return item}
type OrderLine={productId:string;variantId?:string;quantity:number;productName?:string};
export function reserveOrder(orderId:string,branchId:string,items:OrderLine[],userId?:string){const action=`${orderId}:RESERVE`;if(inventoryState.orderActions.has(action))return;for(const line of items){const item=itemFor(branchId,line.productId,line.variantId);if(available(item)<line.quantity)throw new Error(`${line.productName||line.productId} üçün ${line.quantity} ədəd tələb olunur, filialda yalnız ${available(item)} ədəd mövcuddur.`)}for(const line of items){const item=itemFor(branchId,line.productId,line.variantId),before=item.quantity;item.reservedQuantity+=line.quantity;movement(item,"ORDER_RESERVATION",0,before,{referenceType:"ORDER",referenceId:orderId,createdById:userId})}inventoryState.orderActions.add(action);audit("ORDER_RESERVED","Order",orderId,undefined,{branchId,items},userId)}
export function releaseOrder(orderId:string,branchId:string,items:OrderLine[],userId?:string){const action=`${orderId}:RELEASE`;if(inventoryState.orderActions.has(action))return;for(const line of items){const item=itemFor(branchId,line.productId,line.variantId);item.reservedQuantity=Math.max(0,item.reservedQuantity-line.quantity);movement(item,"ORDER_RELEASE",0,item.quantity,{referenceType:"ORDER",referenceId:orderId,createdById:userId})}inventoryState.orderActions.add(action);audit("ORDER_RELEASED","Order",orderId,undefined,{branchId},userId)}
export function fulfillOrder(orderId:string,branchId:string,items:OrderLine[],userId?:string){const action=`${orderId}:FULFILL`;if(inventoryState.orderActions.has(action))return;for(const line of items){const item=itemFor(branchId,line.productId,line.variantId);if(item.reservedQuantity<line.quantity||item.quantity<line.quantity)throw new Error("Sifariş üçün kifayət qədər rezerv stok yoxdur")}for(const line of items){const item=itemFor(branchId,line.productId,line.variantId),before=item.quantity;item.reservedQuantity-=line.quantity;item.quantity-=line.quantity;movement(item,"ORDER_FULFILLMENT",-line.quantity,before,{referenceType:"ORDER",referenceId:orderId,createdById:userId})}inventoryState.orderActions.add(action);audit("ORDER_FULFILLED","Order",orderId,undefined,{branchId},userId)}
export function nextTransferNumber(date=new Date()){const year=date.getFullYear(),next=(inventoryState.transferSequence[year]||0)+1;inventoryState.transferSequence[year]=next;return `TRF-${year}-${String(next).padStart(6,"0")}`}
export function createTransfer(input:{fromBranchId:string;toBranchId:string;items:{productId:string;variantId?:string;quantity:number}[];note?:string;userId?:string}){if(input.fromBranchId===input.toBranchId)throw new Error("Mənbə və təyinat filialı eyni ola bilməz");if(!input.items.length)throw new Error("Transfer məhsulsuz ola bilməz");input.items.forEach(x=>ensurePositive(x.quantity));const transfer:Transfer={id:crypto.randomUUID(),transferNumber:nextTransferNumber(),fromBranchId:input.fromBranchId,toBranchId:input.toBranchId,status:"DRAFT",createdById:input.userId,note:input.note,items:input.items.map(x=>({productId:x.productId,variantId:x.variantId,requestedQuantity:x.quantity,shippedQuantity:0,receivedQuantity:0})),createdAt:new Date().toISOString()};inventoryState.transfers.unshift(transfer);audit("TRANSFER_CREATED","StockTransfer",transfer.id,undefined,transfer,input.userId);return transfer}
export function transitionTransfer(id:string,status:TransferStatus,userId?:string,received?:Record<string,number>){const transfer=inventoryState.transfers.find(x=>x.id===id);if(!transfer)throw new Error("Transfer tapılmadı");const allowed:Record<TransferStatus,TransferStatus[]>={DRAFT:["REQUESTED","CANCELLED"],REQUESTED:["APPROVED","CANCELLED"],APPROVED:["IN_TRANSIT","CANCELLED"],IN_TRANSIT:["RECEIVED"],RECEIVED:[],CANCELLED:[]};if(!allowed[transfer.status].includes(status))throw new Error("Bu transfer keçidi mümkün deyil");const before=structuredClone(transfer),wasApproved=transfer.status==="APPROVED";if(status==="APPROVED"){for(const line of transfer.items){const item=itemFor(transfer.fromBranchId,line.productId,line.variantId);if(available(item)<line.requestedQuantity)throw new Error("Mənbə filialında kifayət qədər stok yoxdur")}for(const line of transfer.items)itemFor(transfer.fromBranchId,line.productId,line.variantId).reservedQuantity+=line.requestedQuantity;transfer.approvedById=userId}if(status==="CANCELLED"&&wasApproved)for(const line of transfer.items){const item=itemFor(transfer.fromBranchId,line.productId,line.variantId);item.reservedQuantity=Math.max(0,item.reservedQuantity-line.requestedQuantity)}if(status==="IN_TRANSIT"){for(const line of transfer.items){const item=itemFor(transfer.fromBranchId,line.productId,line.variantId),old=item.quantity;item.reservedQuantity-=line.requestedQuantity;item.quantity-=line.requestedQuantity;line.shippedQuantity=line.requestedQuantity;movement(item,"TRANSFER_OUT",-line.shippedQuantity,old,{referenceType:"TRANSFER",referenceId:transfer.id,createdById:userId})}transfer.shippedAt=new Date().toISOString()}if(status==="RECEIVED"){for(const line of transfer.items){const amount=received?.[line.productId]??line.shippedQuantity;if(amount<0||amount>line.shippedQuantity)throw new Error("Qəbul miqdarı göndərilən miqdardan çox ola bilməz");const item=itemFor(transfer.toBranchId,line.productId,line.variantId),old=item.quantity;item.quantity+=amount;line.receivedQuantity=amount;movement(item,"TRANSFER_IN",amount,old,{referenceType:"TRANSFER",referenceId:transfer.id,note:amount<line.shippedQuantity?`Fərq: ${line.shippedQuantity-amount}`:undefined,createdById:userId})}transfer.receivedById=userId;transfer.receivedAt=new Date().toISOString()}transfer.status=status;audit("TRANSFER_STATUS_CHANGED","StockTransfer",id,before,transfer,userId);return transfer}
export function canAccessBranch(role:StaffRole,userBranchId:string|undefined,targetBranchId:string){return role==="SUPER_ADMIN"||role==="ADMIN"||role==="WAREHOUSE_MANAGER"||Boolean(userBranchId&&userBranchId===targetBranchId)}
export function dashboard(branchId?:string){const rows=branchId?inventoryState.inventory.filter(x=>x.branchId===branchId):inventoryState.inventory;return{products:new Set(rows.map(x=>x.productId)).size,total:rows.reduce((s,x)=>s+x.quantity,0),reserved:rows.reduce((s,x)=>s+x.reservedQuantity,0),available:rows.reduce((s,x)=>s+available(x),0),low:rows.filter(x=>stockStatus(x)==="LOW_STOCK").length,out:rows.filter(x=>stockStatus(x)==="OUT_OF_STOCK").length,inTransit:inventoryState.transfers.filter(x=>x.status==="IN_TRANSIT").reduce((s,t)=>s+t.items.reduce((a,i)=>a+i.shippedQuantity-i.receivedQuantity,0),0)}}
export function resetInventoryForTests(){inventoryState.branches=structuredClone(demoBranches);inventoryState.inventory=structuredClone(initialInventory);inventoryState.movements=[];inventoryState.transfers=[];inventoryState.audits=[];inventoryState.transferSequence={};inventoryState.orderActions.clear()}
